
nobles = {
  1: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 3,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 0,
    },
  2: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 3,
    },
  3: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 4,
    'brown'  : 4,
    },
  4: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 4,
    'white'  : 4,
    'red'    : 0,
    'brown'  : 0,
    },
  5: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 3,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 3,
    },
  6: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 3,
    'red'    : 3,
    'brown'  : 3,
    },
  7: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 4,
    'red'    : 0,
    'brown'  : 4,
    },
  8: {
    'points' : 3,
    'green'  : 4,
    'blue':  : 4,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 0,
    },
  9: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 3,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 0,
    },
  10: {
    'points' : 3,
    'green'  : 4,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 4,
    'brown'  : 0,
    },
}

cards = {
'large' {
      11: {
        'iden'   : 'green',
        'points' : 4,
        'green'  : 3,
        'blue':  : 6,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 0,
        },
      12: {
        'iden'   : 'red',
        'points' : 3,
        'green'  : 3,
        'blue':  : 5,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 3,
        },
      13: {
        'iden'   : 'white',
        'points' : 4,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 3,
        'brown'  : 6,
        },
      14: {
        'iden'   : 'green',
        'points' : 5,
        'green'  : 3,
        'blue':  : 7,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      15: {
        'iden'   : 'brown',
        'points' : 5,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 7,
        'brown'  : 3,
        },
      16: {
        'iden'   : 'white',
        'points' : 5,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 7,
        },
      17: {
        'iden'   : 'brown',
        'points' : 4,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 7,
        'brown'  : 0,
        },
      18: {
        'iden'   : 'green',
        'points' : 3,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 5,
        'red'    : 3,
        'brown'  : 3,
        },
      19: {
        'iden'   : 'blue',
        'points' : 4,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 7,
        'red'    : 0,
        'brown'  : 0,
        },
      20: {
        'iden'   : 'green',
        'points' : 4,
        'green'  : 0,
        'blue':  : 7,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      21: {
        'iden'   : 'blue',
        'points' : 5,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 7,
        'red'    : 0,
        'brown'  : 0,
        },
      22: {
        'iden'   : 'white',
        'points' : 4,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 7,
        },
      23: {
        'iden'   : 'red',
        'points' : 4,
        'green'  : 6,
        'blue':  : 3,
        'white'  : 0,
        'red'    : 3,
        'brown'  : 0,
        },
      24: {
        'iden'   : 'red',
        'points' : 4,
        'green'  : 7,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      25: {
        'iden'   : 'blue',
        'points' : 3,
        'green'  : 3,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 3,
        'brown'  : 5,
        },
      26: {
        'iden'   : 'brown',
        'points' : 3,
        'green'  : 5,
        'blue':  : 3,
        'white'  : 3,
        'red'    : 3,
        'brown'  : 0,
        },
      27: {
        'iden'   : 'white',
        'points' : 3,
        'green'  : 3,
        'blue':  : 3,
        'white'  : 0,
        'red'    : 5,
        'brown'  : 3,
        },
      28: {
        'iden'   : 'brown',
        'points' : 4,
        'green'  : 3,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 6,
        'brown'  : 3,
        },
      29: {
        'iden'   : 'red',
        'points' : 5,
        'green'  : 7,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 3,
        'brown'  : 0,
        },
      30: {
        'iden'   : 'blue',
        'points' : 4,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 6,
        'red'    : 0,
        'brown'  : 3,
        },
    },
'medium' {
      31: {
        'iden'   : 'green',
        'points' : 2,
        'green'  : 5,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      32: {
        'iden'   : 'white',
        'points' : 1,
        'green'  : 3,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 2,
        'brown'  : 2,
        },
      33: {
        'iden'   : 'brown',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 5,
        'red'    : 0,
        'brown'  : 0,
        },
      34: {
        'iden'   : 'green',
        'points' : 1,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 2,
        'red'    : 0,
        'brown'  : 2,
        },
      35: {
        'iden'   : 'white',
        'points' : 1,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 2,
        'red'    : 3,
        'brown'  : 0,
        },
      36: {
        'iden'   : 'blue',
        'points' : 2,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 5,
        'red'    : 0,
        'brown'  : 0,
        },
      37: {
        'iden'   : 'brown',
        'points' : 2,
        'green'  : 4,
        'blue':  : 1,
        'white'  : 0,
        'red'    : 2,
        'brown'  : 0,
        },
      38: {
        'iden'   : 'red',
        'points' : 2,
        'green'  : 2,
        'blue':  : 4,
        'white'  : 1,
        'red'    : 0,
        'brown'  : 0,
        },
      39: {
        'iden'   : 'red',
        'points' : 1,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 2,
        'red'    : 2,
        'brown'  : 3,
        },
      40: {
        'iden'   : 'brown',
        'points' : 2,
        'green'  : 5,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 3,
        'brown'  : 0,
        },
      41: {
        'iden'   : 'red',
        'points' : 2,
        'green'  : 0,
        'blue':  : 3,
        'white'  : 0,
        'red'    : 2,
        'brown'  : 3,
        },
      42: {
        'iden'   : 'blue',
        'points' : 3,
        'green'  : 0,
        'blue':  : 6,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      43: {
        'iden'   : 'blue',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 2,
        'red'    : 1,
        'brown'  : 4,
        },
      44: {
        'iden'   : 'brown',
        'points' : 3,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 6,
        },
      45: {
        'iden'   : 'red',
        'points' : 3,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 6,
        'brown'  : 0,
        },
      46: {
        'iden'   : 'red',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 5,
        },
      47: {
        'iden'   : 'green',
        'points' : 3,
        'green'  : 6,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      48: {
        'iden'   : 'white',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 5,
        'brown'  : 3,
        },
      49: {
        'iden'   : 'white',
        'points' : 2,
        'green'  : 1,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 4,
        'brown'  : 2,
        },
      50: {
        'iden'   : 'green',
        'points' : 2,
        'green'  : 0,
        'blue':  : 2,
        'white'  : 4,
        'red'    : 0,
        'brown'  : 1,
        },
      51: {
        'iden'   : 'brown',
        'points' : 1,
        'green'  : 2,
        'blue':  : 2,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 0,
        },
      52: {
        'iden'   : 'white',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 5,
        'brown'  : 0,
        },
      53: {
        'iden'   : 'red',
        'points' : 2,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 5,
        },
      54: {
        'iden'   : 'brown',
        'points' : 1,
        'green'  : 3,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 0,
        'brown'  : 2,
        },
      55: {
        'iden'   : 'blue',
        'points' : 1,
        'green'  : 2,
        'blue':  : 2,
        'white'  : 0,
        'red'    : 3,
        'brown'  : 0,
        },
      56: {
        'iden'   : 'green',
        'points' : 2,
        'green'  : 3,
        'blue':  : 5,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      57: {
        'iden'   : 'blue',
        'points' : 2,
        'green'  : 0,
        'blue':  : 5,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 0,
        },
      58: {
        'iden'   : 'white',
        'points' : 3,
        'green'  : 0,
        'blue':  : 0,
        'white'  : 6,
        'red'    : 0,
        'brown'  : 0,
        },
      59: {
        'iden'   : 'blue',
        'points' : 1,
        'green'  : 3,
        'blue':  : 2,
        'white'  : 0,
        'red'    : 0,
        'brown'  : 3,
        },
      60: {
        'iden'   : 'green',
        'points' : 1,
        'green'  : 2,
        'blue':  : 0,
        'white'  : 3,
        'red'    : 3,
        'brown'  : 0,
        },
    },
}