
nobles = {
  1: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 3,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 0,
    },
  2: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 3,
    },
  3: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 4,
    'brown'  : 4,
    },
  4: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 4,
    'white'  : 4,
    'red'    : 0,
    'brown'  : 0,
    },
  5: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 3,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 3,
    },
  6: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 3,
    'red'    : 3,
    'brown'  : 3,
    },
  7: {
    'points' : 3,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 4,
    'red'    : 0,
    'brown'  : 4,
    },
  8: {
    'points' : 3,
    'green'  : 4,
    'blue':  : 4,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 0,
    },
  9: {
    'points' : 3,
    'green'  : 3,
    'blue':  : 3,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 0,
    },
  10: {
    'points' : 3,
    'green'  : 4,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 4,
    'brown'  : 0,
    },
}

cards = {
  11: {
    'iden'   : 'green',
    'points' : 4,
    'green'  : 3,
    'blue':  : 6,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 0,
    },
  12: {
    'iden'   : 'red',
    'points' : 3,
    'green'  : 3,
    'blue':  : 5,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 3,
    },
  13: {
    'iden'   : 'white',
    'points' : 4,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 3,
    'red'    : 3,
    'brown'  : 6,
    },
  14: {
    'iden'   : 'green',
    'points' : 5,
    'green'  : 3,
    'blue':  : 7,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 0,
    },
  15: {
    'iden'   : 'brown',
    'points' : 5,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 7,
    'brown'  : 3,
    },
  16: {
    'iden'   : 'white',
    'points' : 5,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 3,
    'red'    : 0,
    'brown'  : 7,
    },
  17: {
    'iden'   : 'brown',
    'points' : 4,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 7,
    'brown'  : 0,
    },
  18: {
    'iden'   : 'green',
    'points' : 3,
    'green'  : 0,
    'blue':  : 3,
    'white'  : 5,
    'red'    : 3,
    'brown'  : 3,
    },
  19: {
    'iden'   : 'blue',
    'points' : 4,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 7,
    'red'    : 0,
    'brown'  : 0,
    },
  20: {
    'iden'   : 'green',
    'points' : 4,
    'green'  : 0,
    'blue':  : 7,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 0,
    },
  21: {
    'iden'   : 'blue',
    'points' : 5,
    'green'  : 0,
    'blue':  : 3,
    'white'  : 7,
    'red'    : 0,
    'brown'  : 0,
    },
  22: {
    'iden'   : 'white',
    'points' : 4,
    'green'  : 0,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 7,
    },
  23: {
    'iden'   : 'red',
    'points' : 4,
    'green'  : 6,
    'blue':  : 3,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 0,
    },
  24: {
    'iden'   : 'red',
    'points' : 4,
    'green'  : 7,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 0,
    'brown'  : 0,
    },
  25: {
    'iden'   : 'blue',
    'points' : 3,
    'green'  : 3,
    'blue':  : 0,
    'white'  : 3,
    'red'    : 3,
    'brown'  : 5,
    },
  26: {
    'iden'   : 'brown',
    'points' : 3,
    'green'  : 5,
    'blue':  : 3,
    'white'  : 3,
    'red'    : 3,
    'brown'  : 0,
    },
  27: {
    'iden'   : 'white',
    'points' : 3,
    'green'  : 3,
    'blue':  : 3,
    'white'  : 0,
    'red'    : 5,
    'brown'  : 3,
    },
  28: {
    'iden'   : 'brown',
    'points' : 4,
    'green'  : 3,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 6,
    'brown'  : 3,
    },
  29: {
    'iden'   : 'red',
    'points' : 5,
    'green'  : 7,
    'blue':  : 0,
    'white'  : 0,
    'red'    : 3,
    'brown'  : 0,
    },
  30: {
    'iden'   : 'blue',
    'points' : 4,
    'green'  : 0,
    'blue':  : 3,
    'white'  : 6,
    'red'    : 0,
    'brown'  : 3,
    },
}